import AddProperty from '@/components/AddProperty';
import Flexibility from '@/components/Flexibility';
import Hero from '@/components/Hero';
import Mininum from '@/components/Mininum';
import Properties from '@/components/Properties';
import Reviews from '@/components/Reviews';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden bg-white font-inter text-primary">
        <Hero />
        <Mininum />
        <Properties />
        <Flexibility />
        <AddProperty />
        <Reviews />
      </main>
    </>
  );
}
